# Generated by Django 4.2.2 on 2023-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('cad', 'Canadian Dollar'), ('usd', 'United States Dollar'), ('krw', 'Korean Won')], max_length=3),
        ),
    ]
