databases:
  - name: airbnb-clone-database
    plan: free
    databaseName: airbnbclone
    user: airbnbclone

services:
  - type: web
    plan: free
    name: airbnb-clone-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnbclone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
