# Generated by Django 4.2.2 on 2023-12-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0003_alter_photo_file_alter_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='experience',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
