# Generated by Django 4.2.2 on 2023-12-15 21:48

from django.db import migrations, models
import medias.models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(storage=medias.models.S3MediaStorage(), upload_to=''),
        ),
    ]
